name = "x402-socket"
main = "src/index.ts"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

# Static assets
[assets]
directory = "./public"

# KV Namespaces (create via: wrangler kv namespace create <NAME>)
# Then paste the generated IDs below
[[kv_namespaces]]
binding = "USED_TX_HASHES"
id = "4d493c638786485fa908c2c206746f7b"
preview_id = "REPLACE_WITH_PREVIEW_KV_ID"

[[kv_namespaces]]
binding = "AUTH_TOKEN_CACHE"
id = "f8278321a9604c8ba5fabfe84eaf8234"
preview_id = "REPLACE_WITH_PREVIEW_KV_ID"

[[kv_namespaces]]
binding = "SHUTDOWN_TOKENS"
id = "8b7b67de92494e74a420749f1fcb5f31"
preview_id = "f501915250fa4475bceabf09118d3920"

[vars]
CHAIN_ID = "137"
USDC_CONTRACT = "0x2791Bca1f2de4661ED88A30C99A7a9449Aa84174"
PAYMENT_AMOUNT = "0.01"
SOCKET_API_BASE_URL = "https://api.litexmonitor.com"
POWER_ON_DURATION = "15"
WALLETCONNECT_PROJECT_ID = "1c5ee3a710868e6d1c030802ce22ceb7"
RPC_URL = "https://polygon-mainnet.infura.io/v3/a25c51f474ea4d05a9fc8c1515ba767c"
RECEIVER_ADDRESS = "0x1c68552C55526720c36B91BDD2eFAd2F0F7Ad2c7"
SOCKET_API_USER = "aitos"
SOCKET_API_PASSWORD = "a123456"
DEFAULT_DEVICE_PN = "E50000254236686168"
DEFAULT_DEVICE_SN = "DEV19C2B90C3F48E0A"
DEFAULT_DEVICE_DEVADDR = "8"
DEFAULT_DEVICE_DEVCODE = "3000"
